service: project-memory

provider:
  name: google
  runtime: nodejs10
  env: development
  project: plenary-vim-176019
  credentials: ./.gcloud/keyfile.json
  environment: ${file(./serverless.env.json)}

functions:
  graphqlFunction:
    handler: graphql
    events:
      - http: /

plugins:
  - serverless-webpack
  - serverless-google-cloudfunctions
custom:
  serverless-offline:
    port: 4000
  webpack:
    includeModules: true
